---
description: 'Altre informazioni su: C28198'
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
ms.openlocfilehash: 368180985a9541e87c8a74ff912ff29c3b883e03
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/11/2020
ms.locfileid: "97168527"
---
# <a name="c28198"></a>C28198

> avviso C28198: probabile perdita di memoria a causa di un'eccezione.

Questo avviso indica che la memoria allocata non viene liberata dopo la generazione di un'eccezione. L'istruzione alla fine del percorso può generare un'eccezione. La memoria è stata passata a una funzione che potrebbe aver salvato una copia da liberare in un secondo momento.

Questo avviso è molto simile all'avviso [C28197](../code-quality/c28197.md). Le annotazioni consigliate per l'uso con l'avviso [C28197](../code-quality/c28197.md) possono essere usate anche qui.

## <a name="example"></a>Esempio

Nell'esempio riportato di seguito il codice genera questo avviso:

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

Nell'esempio riportato di seguito il codice evita questo avviso:

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
