---
description: 'Altre informazioni su: C28163'
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
ms.openlocfilehash: 89f17f9ef9aaeb6b3dc0710536440ed2fcfbc982
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/11/2020
ms.locfileid: "97303427"
---
# <a name="c28163"></a>C28163

> avviso C28163: la funzione non deve mai essere chiamata dall'interno di un blocco try/except

Questo avviso viene segnalato quando una funzione Ã¨ di un tipo che non deve mai essere racchiuso in un `try/except`  blocco in un `try/except` blocco. Lo strumento di analisi del codice ha rilevato almeno un percorso in cui la funzione chiamata si trovava all'interno di un `try/except` blocco.
